--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: "app:helloworld"
  name: nodehelloworld.example.com
spec: 
  containers: 
    - 
      image: arjunachari12/k8s-demo
      name: k8s-demo
      ports: 
        - 
          containerPort: 3000
          name: nodejs-port
